#!/usr/bin/env python3
"""
Generated Streamlit page template
Auto-generated by Streamlit Tools 🛠️

Table: t_contacts
Display Name: 📇 Contacts
Generated: 2025-08-21T00:26:15.816932
"""

import streamlit as st
import pandas as pd
from datetime import datetime
import sys
import os

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils import *
from ui_layout import COLUMN_PROPS

# Page configuration
st.set_page_config(
    page_title="📇 Contacts",
    page_icon="📇",
    layout="wide"
)

def main():
    """Main page function for 📇 Contacts"""
    
    # Page header
    st.title("📇 Contacts")
    st.markdown("Contact and relationship management with Trinity framework integration")
    
    # Initialize session state
    if "t_contacts_data" not in st.session_state:
        st.session_state["t_contacts_data"] = load_t_contacts_data()
    
    # Sidebar configuration
    with st.sidebar:
        st.header("⚙️ Configuration")
        
        # Search configuration
        st.subheader("🔍 Search Settings")
        search_mode = st.selectbox(
            "Search Mode",
            ["Hybrid", "Semantic", "Keyword"],
            index=0,
            key="t_contacts_search_mode"
        )
        
        # Filters
        
        st.subheader("🏷️ Filters")
        available_tags = get_available_tags("t_contacts")
        selected_tags = st.multiselect(
            "Filter by Tags",
            available_tags,
            key="t_contacts_tags_filter"
        )
        
        
        
        # Additional filters based on list of values
        
        selected_relationship_type = st.multiselect(
            "Filter by Relationship_type",
            ['colleague', 'client', 'mentor', 'vendor', 'partner', 'prospect', 'others'],
            key="t_contacts_relationship_type_filter"
        )
        
        selected_contact_status = st.multiselect(
            "Filter by Contact_status",
            ['active', 'inactive', 'prospect', 'archived'],
            key="t_contacts_contact_status_filter"
        )
        
        
        
        # Actions
        st.subheader("⚡ Actions")
        if st.button("🔄 Refresh Data", key="t_contacts_refresh"):
            st.session_state["t_contacts_data"] = load_t_contacts_data()
            st.rerun()
        
        
        # Import/Export
        if st.button("📤 Export Data", key="t_contacts_export"):
            export_t_contacts_data()
        
        uploaded_file = st.file_uploader(
            "📥 Import CSV", 
            type=['csv'],
            key="t_contacts_import"
        )
        if uploaded_file:
            import_t_contacts_data(uploaded_file)
        
    
    # Main content area
    col1, col2 = st.columns([2, 1])
    
    with col1:
        # Search interface
        st.subheader("🔍 Search 📇 Contacts")
        search_query = st.text_input(
            "Search...",
            placeholder="Enter search terms...",
            key="t_contacts_search_query"
        )
        
        # Execute search
        search_results = perform_search(
            table_name="t_contacts",
            query=search_query,
            mode=search_mode,
            
            tags=selected_tags,
            
            
            filters={
                
                "relationship_type": selected_relationship_type,
                
                "contact_status": selected_contact_status,
                
            }
            
        )
        
        # Display results
        if not search_results.empty:
            st.write(f"Found {len(search_results)} results")
            
            # Data grid with editing capability
            edited_data = st.data_editor(
                search_results,
                use_container_width=True,
                num_rows="dynamic",
                key="t_contacts_data_editor"
            )
            
            # Save changes
            if st.button("💾 Save Changes", key="t_contacts_save_changes"):
                save_t_contacts_changes(edited_data)
                st.success("Changes saved successfully!")
                st.rerun()
        else:
            st.info("No results found. Try different search terms or adjust filters.")
    
    with col2:
        # Add new 📇 contacts form
        st.subheader("➕ Add New Contacts")
        
        with st.form("add_t_contacts", clear_on_submit=True):
            form_data = {}
            
            # Generate form fields based on COLUMN_PROPS
            column_props = COLUMN_PROPS.get("t_contacts", {})
            
            for col_name, props in column_props.items():
                if props.get('is_editable', True) and not props.get('is_system_col', False):
                    widget_type = props.get('widget_type', 'text_input')
                    label = props.get('label_text', col_name.title())
                    tooltip = props.get('tooltip', '')
                    
                    if widget_type == 'text_input':
                        form_data[col_name] = st.text_input(
                            label,
                            help=tooltip,
                            key=f"new_t_contacts_{col_name}"
                        )
                    elif widget_type == 'text_area':
                        form_data[col_name] = st.text_area(
                            label,
                            help=tooltip,
                            key=f"new_t_contacts_{col_name}"
                        )
                    elif widget_type == 'selectbox':
                        options = get_selectbox_options(col_name)
                        form_data[col_name] = st.selectbox(
                            label,
                            options,
                            help=tooltip,
                            key=f"new_t_contacts_{col_name}"
                        )
            
            # Submit button
            if st.form_submit_button("✅ Add Contacts"):
                if validate_t_contacts_data(form_data):
                    save_new_t_contacts(form_data)
                    st.success("Contacts added successfully!")
                    st.session_state["t_contacts_data"] = load_t_contacts_data()
                    st.rerun()
                else:
                    st.error("Please fill in all required fields.")

# Generated utility functions for t_contacts

def load_t_contacts_data():
    """Load all t_contacts data from database"""
    try:
        with DBConn() as conn:
            sql = f"""
                SELECT * FROM t_contacts
                WHERE is_active = 1
                ORDER BY updated_at DESC
            """
            return pd.read_sql(sql, conn)
    except Exception as e:
        st.error(f"Error loading data: {e}")
        return pd.DataFrame()

def perform_search(table_name, query, mode, tags=None, filters=None):
    """Perform search with specified mode and filters"""
    # Implementation would use existing search functions from utils.py
    # This is a placeholder for the actual search logic
    return load_t_contacts_data()

def validate_t_contacts_data(data):
    """Validate t_contacts data before saving"""
    # Add validation logic based on schema requirements
    required_fields = ["contact_name", "created_by", ]
    
    for field in required_fields:
        if not data.get(field):
            return False
    return True

def save_new_t_contacts(data):
    """Save new t_contacts record to database"""
    try:
        # Add system fields
        data.update({
            'created_at': datetime.now().isoformat(),
            'updated_at': datetime.now().isoformat(),
            'created_by': CURRENT_USER,
            'updated_by': CURRENT_USER,
            'is_active': 1
        })
        
        # Use existing db_upsert function from utils.py
        db_upsert("t_contacts", data)
        
        
        # Rebuild search index
        rebuild_search_index("t_contacts")
        
        
    except Exception as e:
        st.error(f"Error saving data: {e}")

def save_t_contacts_changes(edited_data):
    """Save changes from data editor"""
    # Implementation for bulk updates
    pass


def export_t_contacts_data():
    """Export t_contacts data to CSV"""
    data = load_t_contacts_data()
    timestamp = datetime.now().strftime("%Y-%m-%d_%H_%M_%S")
    filename = f"t_contacts-{timestamp}.csv"
    
    csv = data.to_csv(index=False)
    st.download_button(
        label="📥 Download CSV",
        data=csv,
        file_name=filename,
        mime="text/csv"
    )

def import_t_contacts_data(uploaded_file):
    """Import t_contacts data from CSV"""
    try:
        df = pd.read_csv(uploaded_file)
        # Add import logic here
        st.success(f"Imported {len(df)} records")
    except Exception as e:
        st.error(f"Import error: {e}")



def get_available_tags(table_name):
    """Get all available tags for the table"""
    # Implementation to extract unique tags
    return []


def get_selectbox_options(column_name):
    """Get options for selectbox widgets"""
    return SELECTBOX_OPTIONS.get(column_name, [])

if __name__ == "__main__":
    main()