#!/usr/bin/env python3
"""
Generated Streamlit page template
Auto-generated by Streamlit Tools 🛠️

Table: {{ table_name }}
Display Name: {{ display_name }}
Generated: {{ generation_timestamp }}
"""

import streamlit as st
import pandas as pd
from datetime import datetime
import sys
import os

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils import *
from ui_layout import COLUMN_PROPS

# Page configuration
st.set_page_config(
    page_title="{{ display_name }}",
    page_icon="{{ icon }}",
    layout="wide"
)

def main():
    """Main page function for {{ display_name }}"""
    
    # Page header
    st.title("{{ display_name }}")
    st.markdown("{{ description }}")
    
    # Initialize session state
    if "{{ table_name }}_data" not in st.session_state:
        st.session_state["{{ table_name }}_data"] = load_{{ table_name }}_data()
    
    # Sidebar configuration
    with st.sidebar:
        st.header("⚙️ Configuration")
        
        # Search configuration
        st.subheader("🔍 Search Settings")
        search_mode = st.selectbox(
            "Search Mode",
            ["Hybrid", "Semantic", "Keyword"],
            index=0,
            key="{{ table_name }}_search_mode"
        )
        
        # Filters
        {% if features.tag_management %}
        st.subheader("🏷️ Filters")
        available_tags = get_available_tags("{{ table_name }}")
        selected_tags = st.multiselect(
            "Filter by Tags",
            available_tags,
            key="{{ table_name }}_tags_filter"
        )
        {% endif %}
        
        {% if list_of_values %}
        # Additional filters based on list of values
        {% for field, values in list_of_values.items() %}
        selected_{{ field }} = st.multiselect(
            "Filter by {{ field|title }}",
            {{ values }},
            key="{{ table_name }}_{{ field }}_filter"
        )
        {% endfor %}
        {% endif %}
        
        # Actions
        st.subheader("⚡ Actions")
        if st.button("🔄 Refresh Data", key="{{ table_name }}_refresh"):
            st.session_state["{{ table_name }}_data"] = load_{{ table_name }}_data()
            st.rerun()
        
        {% if features.import_export %}
        # Import/Export
        if st.button("📤 Export Data", key="{{ table_name }}_export"):
            export_{{ table_name }}_data()
        
        uploaded_file = st.file_uploader(
            "📥 Import CSV", 
            type=['csv'],
            key="{{ table_name }}_import"
        )
        if uploaded_file:
            import_{{ table_name }}_data(uploaded_file)
        {% endif %}
    
    # Main content area
    col1, col2 = st.columns([2, 1])
    
    with col1:
        # Search interface
        st.subheader("🔍 Search {{ display_name }}")
        search_query = st.text_input(
            "Search...",
            placeholder="Enter search terms...",
            key="{{ table_name }}_search_query"
        )
        
        # Execute search
        search_results = perform_search(
            table_name="{{ table_name }}",
            query=search_query,
            mode=search_mode,
            {% if features.tag_management %}
            tags=selected_tags,
            {% endif %}
            {% if list_of_values %}
            filters={
                {% for field, values in list_of_values.items() %}
                "{{ field }}": selected_{{ field }},
                {% endfor %}
            }
            {% endif %}
        )
        
        # Display results
        if not search_results.empty:
            st.write(f"Found {len(search_results)} results")
            
            # Data grid with editing capability
            edited_data = st.data_editor(
                search_results,
                use_container_width=True,
                num_rows="dynamic",
                key="{{ table_name }}_data_editor"
            )
            
            # Save changes
            if st.button("💾 Save Changes", key="{{ table_name }}_save_changes"):
                save_{{ table_name }}_changes(edited_data)
                st.success("Changes saved successfully!")
                st.rerun()
        else:
            st.info("No results found. Try different search terms or adjust filters.")
    
    with col2:
        # Add new {{ display_name.lower() }} form
        st.subheader("➕ Add New {{ display_name[2:] }}")
        
        with st.form("add_{{ table_name }}", clear_on_submit=True):
            form_data = {}
            
            # Generate form fields based on COLUMN_PROPS
            column_props = COLUMN_PROPS.get("{{ table_name }}", {})
            
            for col_name, props in column_props.items():
                if props.get('is_editable', True) and not props.get('is_system_col', False):
                    widget_type = props.get('widget_type', 'text_input')
                    label = props.get('label_text', col_name.title())
                    tooltip = props.get('tooltip', '')
                    
                    if widget_type == 'text_input':
                        form_data[col_name] = st.text_input(
                            label,
                            help=tooltip,
                            key=f"new_{{ table_name }}_{col_name}"
                        )
                    elif widget_type == 'text_area':
                        form_data[col_name] = st.text_area(
                            label,
                            help=tooltip,
                            key=f"new_{{ table_name }}_{col_name}"
                        )
                    elif widget_type == 'selectbox':
                        options = get_selectbox_options(col_name)
                        form_data[col_name] = st.selectbox(
                            label,
                            options,
                            help=tooltip,
                            key=f"new_{{ table_name }}_{col_name}"
                        )
            
            # Submit button
            if st.form_submit_button("✅ Add {{ display_name[2:] }}"):
                if validate_{{ table_name }}_data(form_data):
                    save_new_{{ table_name }}(form_data)
                    st.success("{{ display_name[2:] }} added successfully!")
                    st.session_state["{{ table_name }}_data"] = load_{{ table_name }}_data()
                    st.rerun()
                else:
                    st.error("Please fill in all required fields.")

# Generated utility functions for {{ table_name }}

def load_{{ table_name }}_data():
    """Load all {{ table_name }} data from database"""
    try:
        with DBConn() as conn:
            sql = f"""
                SELECT * FROM {{ table_name }}
                WHERE is_active = 1
                ORDER BY updated_at DESC
            """
            return pd.read_sql(sql, conn)
    except Exception as e:
        st.error(f"Error loading data: {e}")
        return pd.DataFrame()

def perform_search(table_name, query, mode, tags=None, filters=None):
    """Perform search with specified mode and filters"""
    # Implementation would use existing search functions from utils.py
    # This is a placeholder for the actual search logic
    return load_{{ table_name }}_data()

def validate_{{ table_name }}_data(data):
    """Validate {{ table_name }} data before saving"""
    # Add validation logic based on schema requirements
    required_fields = [{% for col in columns %}{% if 'NOT NULL' in col.constraints %}"{{ col.name }}"{% if not loop.last %}, {% endif %}{% endif %}{% endfor %}]
    
    for field in required_fields:
        if not data.get(field):
            return False
    return True

def save_new_{{ table_name }}(data):
    """Save new {{ table_name }} record to database"""
    try:
        # Add system fields
        data.update({
            'created_at': datetime.now().isoformat(),
            'updated_at': datetime.now().isoformat(),
            'created_by': CURRENT_USER,
            'updated_by': CURRENT_USER,
            'is_active': 1
        })
        
        # Use existing db_upsert function from utils.py
        db_upsert("{{ table_name }}", data)
        
        {% if features.semantic_search %}
        # Rebuild search index
        rebuild_search_index("{{ table_name }}")
        {% endif %}
        
    except Exception as e:
        st.error(f"Error saving data: {e}")

def save_{{ table_name }}_changes(edited_data):
    """Save changes from data editor"""
    # Implementation for bulk updates
    pass

{% if features.import_export %}
def export_{{ table_name }}_data():
    """Export {{ table_name }} data to CSV"""
    data = load_{{ table_name }}_data()
    timestamp = datetime.now().strftime("%Y-%m-%d_%H_%M_%S")
    filename = f"{{ table_name }}-{timestamp}.csv"
    
    csv = data.to_csv(index=False)
    st.download_button(
        label="📥 Download CSV",
        data=csv,
        file_name=filename,
        mime="text/csv"
    )

def import_{{ table_name }}_data(uploaded_file):
    """Import {{ table_name }} data from CSV"""
    try:
        df = pd.read_csv(uploaded_file)
        # Add import logic here
        st.success(f"Imported {len(df)} records")
    except Exception as e:
        st.error(f"Import error: {e}")
{% endif %}

{% if features.tag_management %}
def get_available_tags(table_name):
    """Get all available tags for the table"""
    # Implementation to extract unique tags
    return []
{% endif %}

def get_selectbox_options(column_name):
    """Get options for selectbox widgets"""
    return SELECTBOX_OPTIONS.get(column_name, [])

if __name__ == "__main__":
    main()